version: '2.1'

services:
  elasticsearch:
    container_name: elasticsearch
    image: mwangxx/elasticsearch:7.6.0
    volumes:
      - $HOME/BulletJournal/elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - $HOME/docker/volumes/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms128m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.6.0
    volumes:
      - $HOME/BulletJournal/elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  
  # logstash:
  #   container_name: logstash
  #   build:
  #     context: $HOME/BulletJournal/elk/logstash/
  #     args:
  #       ELK_VERSION: 7.6.0
  #   volumes:
  #     - $HOME/BulletJournal/elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
  #     - $HOME/BulletJournal/elk/logstash/pipeline:/usr/share/logstash/pipeline
  #   ports:
  #     - "5000:5000/tcp"
  #     - "5000:5000/udp"
  #     - "9600:9600"
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx512m -Xms256m"
  #     postgres_hostname: db
  #     postgres_jdbc_driver_absolute_path: /usr/share/logstash/logstash-core/lib/jars/postgresql.jar
  #     logstash_last_run_metadata_absolute_path: /usr/share/logstash/.logstash_jdbc_last_run
  #     elasticsearch_hostname: elasticsearch
  #   depends_on:
  #     - elasticsearch
